version: '3.1'

services:
  db:
    image: propertybeacon/postgres
    restart: always
    environment:
      POSTGRES_DB: pb
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  pgadmin:
    image: propertybeacon/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@propertybeacon.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
